apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    owner: Vishal
  name: mysql
  namespace: nsmysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 172611943020.dkr.ecr.us-east-1.amazonaws.com/db_mysql:latest
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password