apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: nsmysql
  labels:
    owner: Vishal
spec:
  containers:
  - name: mysql
    image: 172611943020.dkr.ecr.us-east-1.amazonaws.com/db_mysql:latest
    ports:
    - name: mysql
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
