apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlreplicaset
  namespace: nsmysql
  labels:
    app: mysql
    owner: Vishal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 172611943020.dkr.ecr.us-east-1.amazonaws.com/db_mysql:latest
        name: mysql
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password